### PR TITLE
noarch: python packages are built once

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jakirkham** [comment]
Would it be worth adding some recipe tests too?

Edit: I had some in this PR ( https://github.com/conda-forge/conda-build-all/pull/7 ), which might be worth taking. Was trying out a different way of solving this problem, but yours seems cleaner.

**Comment by jjhelmus** [comment]
Added a recipe test.

**Comment by jakirkham** [comment]
Toggling to retest with current `master`.

**Comment by jakirkham** [comment]
One small note, which is not relevant to the conda-forge use case, but is relevant to `conda-build-all` users. It seems that `conda-build-all` is unable to recognize when it has already built a `noarch: python` package. Whereas with a normal Python package, it recognizes when it has already built one version and skips it. I'm not entirely sure where this logic lives, but this seems like something worth checking out or at a bare minimum raising an issue for later.

Edit: This [`find_existing_built_dists`]( https://github.com/conda-forge/conda-build-all/blob/ed4f1039e4df01b5b4f432aee7186f229458382b/conda_build_all/builder.py#L176 ) function seems relevant.

Edit 2: Have found a fix for this issue and have pushed a commit that seems to address the problem.

**Comment by jakirkham** [comment]
FWIW tested the upload feature and that seems to behave correctly with this change.

**Comment by jakirkham** [comment]
Could you please take a look at this PR as well, @mwcraig? It seems like you are pretty involved with `conda-build-all` and so may be able to catch things that we may miss.

**Comment by jakirkham** [comment]
FYI have pushed a small commit to this PR to fix failed detection of existing `noarch: python` packages. Hope that is ok.

**Comment by mwcraig** [comment]
This looks ok, though I've never tried building `noarch` packages so my experience there is limited.

>  It seems like you are pretty involved with conda-build-all and so may be able to catch things that we may miss.

🤣  😳  🤣 

Thanks...but it might be more accurate to say that I'm unusually good at breaking it...

**Comment by jakirkham** [comment]
Thanks for taking a look @mwcraig.

> ...it might be more accurate to say that I'm unusually good at breaking it...

So the story of a software developer then? 😜

**Comment by jakirkham** [comment]
Are you ok with the last commit, @jjhelmus? If so, I think we should merge this.

**Comment by jakirkham** [comment]
I just merged as we are trying to migrate this.

**Pull request merged**
